### ISSUE TITLE
Tutorial feedback items from walkthrough users 

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/docs#233]
Below are some of the items the users felt we could add some instructions 
- [x] Open in a new terminal to run Azure service principal creation 
- [ ] Edge version should point to edge version of rad cli - #268 
- [ ] Container/resources - explain how they add their own container /mongo db  - #269
- [x] AKS - Register Kubernetes cluster in kube config
- [ ] Docker desktop doesn’t wrk on Mac apple m1 proc - #270

**Comment by amanbha** [comment]
triage notes: committed for 0.12

**Comment by Reshrahim** [comment]
Created separate items to track the pending items. Closing this issue
