### ISSUE TITLE
Add documentation for connection values and secrets to resource reference pages

### ISSUE THREAD

**Issue by rynowak** [radius-project/docs#657]
## What content needs to be created or modified?

This [docs page](https://docs.radapp.dev/concepts/appmodel-concept/#injected-values) has a section on connection values and secrets which it refers to as *injected values*. 

This page goes on to say:

> Each kind of connection defines values that are useful for communication. These could be URIs, connection strings, access keys, or anything that application code needs to successfully communicate. Refer to each [resource’s reference documentation](https://docs.radapp.dev/reference/resource-schema/) for more information.

Currently this information is missing from the reference pages.

## Describe the solution you'd like

Things are missing:

- A description of the convention that Radius follows. (The convention is mentioned but not documented and there are no examples.)
- The fact that the convention uses environment variables is not covered.
- A description of the alternative to our convention: (Define your own environment variables.)
- Each resource page needs to describe the values that are set with examples and descriptions of the appropriate formats. 

## Where should the new material be placed?

A few points need to be added to: https://docs.radapp.dev/concepts/appmodel-concept/#injected-values

The resource reference pages each need an update

## Additional context

User-reported issue.

[AB#8835](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/8835)
```[tasklist]
### Tasks
- [x] A description of the convention that Radius follows. (The convention is mentioned but not documented and there are no examples.)
- [x] The fact that the convention uses environment variables is not covered.
- [x] A description of the alternative to our convention: (Define your own environment variables.)
- [x] Each resource page needs to describe the values that are set with examples and descriptions of the appropriate formats.
```
